"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Reclaim__factory = exports.IReclaim__factory = exports.DappSmartContract__factory = exports.lib = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.lib = __importStar(require("./lib"));
var DappSmartContract__factory_1 = require("./DappSmartContract__factory");
Object.defineProperty(exports, "DappSmartContract__factory", { enumerable: true, get: function () { return DappSmartContract__factory_1.DappSmartContract__factory; } });
var IReclaim__factory_1 = require("./IReclaim__factory");
Object.defineProperty(exports, "IReclaim__factory", { enumerable: true, get: function () { return IReclaim__factory_1.IReclaim__factory; } });
var Reclaim__factory_1 = require("./Reclaim__factory");
Object.defineProperty(exports, "Reclaim__factory", { enumerable: true, get: function () { return Reclaim__factory_1.Reclaim__factory; } });
