"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SemaphoreInterface__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var SemaphoreInterface__factory_1 = require("./SemaphoreInterface__factory");
Object.defineProperty(exports, "SemaphoreInterface__factory", { enumerable: true, get: function () { return SemaphoreInterface__factory_1.SemaphoreInterface__factory; } });
