"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PoseidonT6__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256[5]",
                name: "",
                type: "uint256[5]",
            },
        ],
        name: "poseidon",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
];
const _bytecode = "0x61012161003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80634937a258146038575b600080fd5b60496043366004605b565b50600090565b60405190815260200160405180910390f35b600060a08284031215606b578081fd5b82601f8301126078578081fd5b60405160a0810181811067ffffffffffffffff82111715609857609860d5565b604052808360a0810186101560ab578384fd5b835b600581101560ca57813583526020928301929091019060010160ad565b509195945050505050565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220bfe8b2dca18bb102fd00396105dd959e20705dc3ceb91044b3d486801e4c3c5d64736f6c63430008040033";
const isSuperArgs = (xs) => xs.length > 1;
class PoseidonT6__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.PoseidonT6__factory = PoseidonT6__factory;
PoseidonT6__factory.bytecode = _bytecode;
PoseidonT6__factory.abi = _abi;
