"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PoseidonT3__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256[2]",
                name: "",
                type: "uint256[2]",
            },
        ],
        name: "poseidon",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
];
const _bytecode = "0x61012361003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806329a5f2f6146038575b600080fd5b60496043366004605b565b50600090565b60405190815260200160405180910390f35b600060408284031215606b578081fd5b82601f8301126078578081fd5b6040516040810181811067ffffffffffffffff82111715609857609860d7565b806040525080838560408601111560ad578384fd5b835b600281101560cc57813583526020928301929091019060010160af565b509195945050505050565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220f778cfd80413ef4cc42c97cda70c405908c003bcc07d0eeba2b344c1827cb0e564736f6c63430008040033";
const isSuperArgs = (xs) => xs.length > 1;
class PoseidonT3__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.PoseidonT3__factory = PoseidonT3__factory;
PoseidonT3__factory.bytecode = _bytecode;
PoseidonT3__factory.abi = _abi;
