"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISemaphoreVerifier__factory = exports.ISemaphoreGroups__factory = exports.ISemaphore__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISemaphore__factory_1 = require("./ISemaphore__factory");
Object.defineProperty(exports, "ISemaphore__factory", { enumerable: true, get: function () { return ISemaphore__factory_1.ISemaphore__factory; } });
var ISemaphoreGroups__factory_1 = require("./ISemaphoreGroups__factory");
Object.defineProperty(exports, "ISemaphoreGroups__factory", { enumerable: true, get: function () { return ISemaphoreGroups__factory_1.ISemaphoreGroups__factory; } });
var ISemaphoreVerifier__factory_1 = require("./ISemaphoreVerifier__factory");
Object.defineProperty(exports, "ISemaphoreVerifier__factory", { enumerable: true, get: function () { return ISemaphoreVerifier__factory_1.ISemaphoreVerifier__factory; } });
