"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISemaphoreVerifier__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "merkleTreeRoot",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "nullifierHash",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "signal",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "externalNullifier",
                type: "uint256",
            },
            {
                internalType: "uint256[8]",
                name: "proof",
                type: "uint256[8]",
            },
            {
                internalType: "uint256",
                name: "merkleTreeDepth",
                type: "uint256",
            },
        ],
        name: "verifyProof",
        outputs: [],
        stateMutability: "view",
        type: "function",
    },
];
class ISemaphoreVerifier__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ISemaphoreVerifier__factory = ISemaphoreVerifier__factory;
ISemaphoreVerifier__factory.abi = _abi;
